{% set version = "23.3.0" %}

package:
  name: sanic-testing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sanic-testing/sanic-testing-{{ version }}.tar.gz
  sha256: 2328d86045886099d8ecbf7889f5c1377bcb98b769955680224945d9de198613

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - httpx >=0.18,<0.24

test:
  imports:
    - sanic_testing
  commands:
    - pip check
  requires:
    - pip
    - sanic

about:
  home: https://github.com/sanic-org/sanic-testing/
  summary: Core testing clients for Sanic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
