{% set version = "24.6.0" %}

package:
  name: sanic-testing
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sanic-testing/sanic_testing-{{ version }}.tar.gz
  sha256: 7591ce537e2a651efb6dc01b458e7e4ea5347f6d91438676774c6f505a124731

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - httpx >=0.18
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
    - sanic
  imports:
    - sanic_testing
  commands:
    - pip check
  
about:
  home: https://github.com/sanic-org/sanic-testing/
  summary: Core testing clients for Sanic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
