{% set version = "23.12.0" %}

package:
  name: sanic-testing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sanic-testing/sanic-testing-{{ version }}.tar.gz
  sha256: 2b9c52b7314b7e1807958f41581e18b8254c5161c953e70fcf492e0dd2fe133f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - httpx >=0.18
    - python >=3.8

test:
  imports:
    - sanic_testing
  commands:
    - pip check
  requires:
    - pip
    - sanic

about:
  home: https://github.com/sanic-org/sanic-testing/
  summary: Core testing clients for Sanic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
